### PR TITLE
Escape-quote `groups` mysql 8 reserved keyword, closes #5

### LINKED ISSUE #5: Errors due to "groups" after MySQL 8.0 upgrade
After upgrading to MySQL 8.0 I started getting SQL errors in my Piwigo installation from the plugin. I tracked it down to needing to add backticks around "groups" (which is reserved word now) on line 532:

```
    $sql="SELECT COUNT(id) AS nbGroup
          FROM `".GROUPS_TABLE."`;";
```

and line 556:

```
    $sql="SELECT id, `order`, users, `groups`
          FROM ".$this->tables['blocks']."
```

### PR DESCRIPTION
**Pull request by erAck**

### CODE REVIEW

**Comment by erAck** [comment]
@plegall: interested in merging this?

**Comment by erAck** [comment]
@plegall bump?

**Comment by Grotax** [comment]
@erAck thanks applied the patch locally, works :+1:

**Comment by erAck** [comment]
@plegall 
Will this now that https://github.com/Piwigo/Piwigo/commit/1ec5a2933cbd221a32556fdca6ea54e076f60383 removes the `groups` club from Piwigo be finally considered for a merge? Else this extension will break again.

**Pull request merged**
